backend:
  name: github
  repo: AlexTesterLabs/gatsby-blog-master

media_folder: static/img
public_folder: "img"

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "blog" }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: image, label: Image,  widget: image, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: news
    label: News
    folder: src/pages/news
    create: true
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "news" }
      - { name: title, label: Title }
      - { name: link, label: Link }
      - { name: body, label: Body, widget: markdown }
